### PR TITLE
Short explanation on how to fix acrobat DC issue, #131

### PR DESCRIPTION
**Pull request by kba**
I don't know the issue, feel free to reword/correct as required.

### CODE REVIEW

**Comment by zuphilip** [comment]
Okay, I will extend that a little.

**Comment by kba** [comment]
Could also be a custom Troubleshooting guide, https://github.com/UB-Mannheim/sci-work-course/issues/99. Many problems are probably platform-specific though.

**Comment by zuphilip** [comment]
Here is my update. Any comments? (I think to add this here in the windows specific installation guide makes more sense than a generic troubleshouting page.)

**Comment by kba** [comment]
Looks good. Must be merged to vanilla, I opened the PR to master and cannot change now.

**Comment by zuphilip** [comment]
Yes, we should change the branch. But you can actually do this quite easily (some new feature of GitHub):
 * Click on `Edit` here on the top of the page
 * Change the branch to `vanilla`

**Comment by kba** [comment]
Haha, that went well.

**Comment by kba** [comment]
I'll better cherry-pick on the command line :D

**Comment by kba** [comment]
Merged to vanilla https://github.com/UB-Mannheim/sci-work-course/tree/vanilla

**Comment by zuphilip** [comment]
Thank you!

**Pull request closed without merging**
