### PR TITLE
commit birth dates

### PR DESCRIPTION
**Pull request by sceeptex**
Hello this is my pull request to add the birth dates

### CODE REVIEW

**Review by stweil — CHANGES_REQUESTED** [review]
You did a great job, but updating a single file (for example 01.txt) would have been sufficient. If I merged your pull request, there would nothing remain for others. Could you please update the commit to only change a single file?

**Comment by sceeptex** [comment]
Hello, i changed some dates to ????

**Comment by stweil** [comment]
Okay, I now merged a part of your first commit which only changes `01.txt`, see commit 687a67909ae9250ec92d907c57db0d67e16ccc51. Thanks again.

I also noticed that `git log` does not show your real name. For this exercise your real name is not mandatory, but for real work with git I suggest to set your name using `git config --edit --global`. If you want, you can also set it in your personal GitHub settings, so https://github.com/sceeptex would show your real name.

**Comment by stweil** [comment]
Okay, I now merged a part of your first commit which only changes `01.txt`, see commit 687a67909ae9250ec92d907c57db0d67e16ccc51. Thanks again.

I also noticed that `git log` does not show your real name. For this exercise your real name is not mandatory, but for real work with git I suggest to set your name using `git config --edit --global`. If you want, you can also set it in your personal GitHub settings, so https://github.com/sceeptex would show your real name.

**Pull request closed without merging**
